# Generated by Django 2.2.6 on 2020-01-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenueList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_list', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('distance', models.DecimalField(decimal_places=25, max_digits=50)),
                ('venues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='tour.VenueList')),
            ],
        ),
    ]
